### ISSUE TITLE
[Suggestion] No ESP

### ISSUE THREAD

**Issue by ga6rielsilva** [Incandescent-Turtle/FriendHighlighter#7]
Could you create a version of this mod where you can't see other players/entities through walls?

**Comment by Incandescent-Turtle** [comment]
> Could you create a version of this mod where you can't see other players/entities through walls?

Thanks for the suggestion! Thinking about this, yes I do think this is possible. I should be able to disable the outline rendering if a player shouldn't be visible. I will add it to my list--that is a great idea.

However I am quite busy with university and other activities, so it might be a bit till this feature is added!

**Comment by Incandescent-Turtle** [comment]
@ga6rielsilva are you looking for this feature to be added for a specific version of minecraft? i can prioritize releasing the feature for that version first

**Comment by ga6rielsilva** [comment]
@Incandescent-Turtle I play on 1.20.1, if you could get to that version first it would be amazing.

And could you also add an option to highlight all players?

**Comment by Incandescent-Turtle** [comment]
> And could you also add an option to highlight all players?

This has now been added as an expiremental feature. At this time there has been no implementation of No ESP though. Next month there will be a bigger release that may include that feature though

highlight all players here - https://github.com/Incandescent-Turtle/FriendHighlighter/releases/tag/expiremental-1.20.1

**Comment by Incandescent-Turtle** [comment]
no-ESP (highlighting through blocks) has officially been added in v1.1.0 to versions 1.19.2, 1.19.4, 1.20.1-1.20.4. They can be downloaded on curseforge
