### ISSUE TITLE
Unable Launch on Startup

### ISSUE THREAD

**Issue by MrWorseThanAll** [Incandescent-Turtle/FriendHighlighter#8]
![Startupcrash](https://github.com/user-attachments/assets/47171695-9804-415e-a1f1-2049e6bac3bd)
![Startupcrash](https://github.com/user-attachments/assets/de6a4212-2d16-4fe9-b2c3-a4fb4b0f570e)
When i attempt to load this game, it says its not compatible with 1.21.1 despite being only 1.21
there were no other files that could work and my modpack is pretty light, not sure if theres anything i can do about this, if you have any suggestions let me know

**Comment by Incandescent-Turtle** [comment]
Hi, sorry you're having a problem! To clarify, which version of minecraft are you using? 1.21 or 1.21.1? And what is the filename of mod (and did you get it from curseforge?)

**Comment by MrWorseThanAll** [comment]
I got it from curseforge
Im using fabric
0.16 according to the loader window
Im using (1.21.1)
And looking at the "version's" tab.
There is only one file compatible with my pack (and shown

**Comment by Incandescent-Turtle** [comment]
okay i have replicated this issue and i am fixing it right now. should be fixed within an hour

**Comment by Incandescent-Turtle** [comment]
this should now be fixed, a new file is being uploaded to curseforge

**Comment by MrWorseThanAll** [comment]
Thank you for your good work, i will find out if it works in about 3 - 4 hours
Im looking into this bc in my friend's realm i found everyone was cheating but now we just having fun
