### ISSUE TITLE
Modrinth Distribution 

### ISSUE THREAD

**Issue by breon** [Incandescent-Turtle/FriendHighlighter#9]
Hi there, 
Can you also distribute this mod via Modrinth? 

Thanks!
Breon

**Comment by Incandescent-Turtle** [comment]
Unfortunately, I cannot, they classify it as a cheat, which they have policies against. Since this is purely client side with no server verification they won't allow it--I would have to make it a serverside mod/plugin too for it to be on Modrinth, which I have no current plans to do

**Comment by breon** [comment]
Thanks for the response.
